package com.example.natour.entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;

@Entity(tableName = "simple_itinerary")
public class SimpleItinerary {

    // id autogenerated just for local db, useless for itinerary purposes
    @PrimaryKey(autoGenerate = true)
    public int id_db;

    @ColumnInfo()
    public int id;

    @ColumnInfo()
    public String title = null;

    @ColumnInfo()
    public String description = null;

    @ColumnInfo(name = "list_type")
    public String listType = null;

    public SimpleItinerary(){

    }

    public SimpleItinerary(int id, String title, String description){
        this.id = id;
        this.title = title;
        this.description = description;
    }

    public SimpleItinerary(int id, String title, String description, String listType) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.listType = listType;
    }

    @NonNull
    @Override
    public String toString() {
        StringBuilder output = new StringBuilder();

        output.append("Itinerary { \n\r");
        output.append(" Owner: ").append(id).append("\n\r");
        output.append(" Title: ").append(title).append("\n\r");
        output.append(" List Type: ").append(listType).append("\n\r");

        output.append("---------- END ----------\n\r");

        return output.toString();
    }


}