CREATE TABLE List(
	idList bigint AUTO_INCREMENT PRIMARY KEY,
	type varchar(25) NOT NULL,
    email varchar(320) NOT NULL,
    CONSTRAINT f5 FOREIGN KEY(email) REFERENCES User(email)
		ON DELETE CASCADE
        	ON UPDATE CASCADE,
	CONSTRAINT f6 FOREIGN KEY(type) REFERENCES ListTypeEnum(type)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);